### PR TITLE
Fix a few typos in week03

### PR DESCRIPTION
**Pull request by JosefVitu**
Hi, just a few typos I noticed.

### CODE REVIEW

**Comment by cjdb** [comment]
Hi, thanks!

Would you mind making the edits to [asciidoc/week03.asciidoc](https://github.com/cjdb/COMP6771-AdvancedCppProgramming/blob/master/asciidoc/week03.asciidoc), please? The HTML is generated from the Asciidoc.

**Comment by JosefVitu** [comment]
Sorry, will do.

**Comment by JosefVitu** [comment]
Alright, done.

**Comment by cjdb** [comment]
Thanks!

**Pull request merged**
